name: Update Contributors

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  update_contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update contributor list in README
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: README.md
          commit_message: "docs(readme): update contributors list"
          use_username: true
          image_size: 100
          columns_per_row: 6
          collaborators: "all"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update contributor list in README_ENG
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: README_ENG.md
          commit_message: "docs(readme): update contributors list"
          use_username: true
          image_size: 100
          columns_per_row: 6
          collaborators: "all"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}