name: Update Contributors

on:
  push:
    branches:
      - main

jobs:
  update_contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Update contributor list in README
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: README.md
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Update contributor list in README_ENG
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: README_ENG.md
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
